-- Auto-generated by supabase/scripts/prepare_louisiana_seed.py
begin;

insert into organizations (id, slug, name, type, industry_sector, region, description, headquarters, metadata, created_at, updated_at)
values ('fa951fa4-2760-5db1-8a05-0b9ecfb2da67', 'pdv-america-inc', 'PDV America Inc', 'company', 'fossil-fuel-operations', 'Louisiana', NULL, '{"state": "LA", "country": "USA"}', '{"source_types": ["Deep conversion Coking-FCC-GO-HC-6"], "reporting_entities": ["climate-trace"]}', now(), now())
on conflict (slug) do update set name = excluded.name, industry_sector = excluded.industry_sector, metadata = excluded.metadata;

insert into organizations (id, slug, name, type, industry_sector, region, description, headquarters, metadata, created_at, updated_at)
values ('f78a7b15-df16-5a21-9f18-b1cff3aa4382', 'climate-trace', 'climate-trace', 'company', 'transportation', 'Louisiana', NULL, '{"state": "LA", "country": "USA"}', '{"source_types": ["Hydroskimming-0", "domestic", "hydrogen_production", "manufacturing"], "reporting_entities": ["climate-trace"]}', now(), now())
on conflict (slug) do update set name = excluded.name, industry_sector = excluded.industry_sector, metadata = excluded.metadata;

insert into organizations (id, slug, name, type, industry_sector, region, description, headquarters, metadata, created_at, updated_at)
values ('5c60a4e0-dab5-5090-b0f5-435b4ff0cd7e', 'lotte-group', 'Lotte Group', 'company', 'manufacturing', 'Louisiana', NULL, '{"state": "LA", "country": "USA"}', '{"source_types": ["Natural Gas Liquids"], "reporting_entities": ["climate-trace"]}', now(), now())
on conflict (slug) do update set name = excluded.name, industry_sector = excluded.industry_sector, metadata = excluded.metadata;

insert into organizations (id, slug, name, type, industry_sector, region, description, headquarters, metadata, created_at, updated_at)
values ('dd092091-5a90-591d-97ad-ead8411a3205', 'lyondellbasell-industries-nv', 'LyondellBasell Industries NV', 'company', 'manufacturing', 'Louisiana', NULL, '{"state": "LA", "country": "USA"}', '{"source_types": ["Natural Gas Liquids"], "reporting_entities": ["climate-trace"]}', now(), now())
on conflict (slug) do update set name = excluded.name, industry_sector = excluded.industry_sector, metadata = excluded.metadata;

insert into organizations (id, slug, name, type, industry_sector, region, description, headquarters, metadata, created_at, updated_at)
values ('7f206c78-abbb-5a9d-a6e9-e46aace4727d', 'rain-cii-carbon-llc', 'Rain CII Carbon LLC', 'company', 'power', 'Louisiana', NULL, '{"state": "LA", "country": "USA"}', '{"source_types": ["other_fossil"], "reporting_entities": ["climate-trace"]}', now(), now())
on conflict (slug) do update set name = excluded.name, industry_sector = excluded.industry_sector, metadata = excluded.metadata;

insert into organizations (id, slug, name, type, industry_sector, region, description, headquarters, metadata, created_at, updated_at)
values ('4f9c6696-1c12-52e3-b9c7-79d3db5e0063', 'equistar-chemicals-lp', 'Equistar Chemicals LP', 'company', 'power', 'Louisiana', NULL, '{"state": "LA", "country": "USA"}', '{"source_types": ["gas"], "reporting_entities": ["climate-trace"]}', now(), now())
on conflict (slug) do update set name = excluded.name, industry_sector = excluded.industry_sector, metadata = excluded.metadata;

insert into organizations (id, slug, name, type, industry_sector, region, description, headquarters, metadata, created_at, updated_at)
values ('bd206abe-875a-5a79-bfb0-9f83ae0f67ef', 'entergy-corp', 'Entergy Corp', 'company', 'power', 'Louisiana', NULL, '{"state": "LA", "country": "USA"}', '{"source_types": ["gas"], "reporting_entities": ["climate-trace"]}', now(), now())
on conflict (slug) do update set name = excluded.name, industry_sector = excluded.industry_sector, metadata = excluded.metadata;

insert into facilities (id, org_id, slug, name, facility_type, latitude, longitude, metadata, visibility, created_at, updated_at)
values ('81d3ce08-fa85-50ef-af7a-8f543fbdc21d', 'fa951fa4-2760-5db1-8a05-0b9ecfb2da67', 'citgo-lake-charles-refinery', 'Citgo Lake Charles Refinery', 'oil-and-gas-refining', 30.181174, -93.332596, '{"subsector": "oil-and-gas-refining", "epa_or_state_id": "1753272"}', 'org', now(), now())
on conflict (id) do update set name = excluded.name, facility_type = excluded.facility_type, latitude = excluded.latitude, longitude = excluded.longitude, metadata = excluded.metadata, visibility = excluded.visibility;

insert into facilities (id, org_id, slug, name, facility_type, latitude, longitude, metadata, visibility, created_at, updated_at)
values ('699dc94e-18c0-5075-a64d-44940613f9dd', 'f78a7b15-df16-5a21-9f18-b1cff3aa4382', 'transworld-oil-usa-lake-charles-refinery', 'Transworld Oil USA Lake Charles Refinery', 'oil-and-gas-refining', 30.132389, -93.320068, '{"subsector": "oil-and-gas-refining", "epa_or_state_id": "1753316"}', 'org', now(), now())
on conflict (id) do update set name = excluded.name, facility_type = excluded.facility_type, latitude = excluded.latitude, longitude = excluded.longitude, metadata = excluded.metadata, visibility = excluded.visibility;

insert into facilities (id, org_id, slug, name, facility_type, latitude, longitude, metadata, visibility, created_at, updated_at)
values ('07839aab-ecf7-58f3-a7f7-064aaa27d77f', 'f78a7b15-df16-5a21-9f18-b1cff3aa4382', 'air-products-chemical-inc-lake-charles-facility', 'AIR PRODUCTS & CHEMICAL INC - LAKE CHARLES FACILITY', 'other-chemicals', 30.238889, -93.281944, '{"subsector": "other-chemicals", "epa_or_state_id": "3674401"}', 'org', now(), now())
on conflict (id) do update set name = excluded.name, facility_type = excluded.facility_type, latitude = excluded.latitude, longitude = excluded.longitude, metadata = excluded.metadata, visibility = excluded.visibility;

insert into facilities (id, org_id, slug, name, facility_type, latitude, longitude, metadata, visibility, created_at, updated_at)
values ('39f7ccc0-25f9-5c43-8ee3-65a1ce6c08e2', 'f78a7b15-df16-5a21-9f18-b1cff3aa4382', 'firestone-polymers-lake-charles-facility', 'FIRESTONE POLYMERS - LAKE CHARLES FACILITY', 'other-manufacturing', 30.186144, -93.331209, '{"subsector": "other-manufacturing", "epa_or_state_id": "3193127"}', 'org', now(), now())
on conflict (id) do update set name = excluded.name, facility_type = excluded.facility_type, latitude = excluded.latitude, longitude = excluded.longitude, metadata = excluded.metadata, visibility = excluded.visibility;

insert into facilities (id, org_id, slug, name, facility_type, latitude, longitude, metadata, visibility, created_at, updated_at)
values ('2369cf61-6ef0-52cc-b1bf-ed1531092c0e', '5c60a4e0-dab5-5090-b0f5-435b4ff0cd7e', 'axial-lotte-lake-charles-la', 'Axial/Lotte, Lake Charles, La', 'petrochemical-steam-cracking', 30.224502, -93.304322, '{"subsector": "petrochemical-steam-cracking", "epa_or_state_id": "18648338"}', 'org', now(), now())
on conflict (id) do update set name = excluded.name, facility_type = excluded.facility_type, latitude = excluded.latitude, longitude = excluded.longitude, metadata = excluded.metadata, visibility = excluded.visibility;

insert into facilities (id, org_id, slug, name, facility_type, latitude, longitude, metadata, visibility, created_at, updated_at)
values ('e7fc3e4f-1171-5a75-b451-7807d3be9255', 'dd092091-5a90-591d-97ad-ead8411a3205', 'sasol-lyondellbassell-lake-charles-la', 'Sasol/LyondellBassell, Lake Charles,La', 'petrochemical-steam-cracking', 30.245803, -93.274281, '{"subsector": "petrochemical-steam-cracking", "epa_or_state_id": "18648328"}', 'org', now(), now())
on conflict (id) do update set name = excluded.name, facility_type = excluded.facility_type, latitude = excluded.latitude, longitude = excluded.longitude, metadata = excluded.metadata, visibility = excluded.visibility;

insert into facilities (id, org_id, slug, name, facility_type, latitude, longitude, metadata, visibility, created_at, updated_at)
values ('212fda08-74b9-5110-a424-35936d7c1cf0', '7f206c78-abbb-5a9d-a6e9-e46aace4727d', 'lake-charles-plant', 'Lake Charles Plant', 'electricity-generation', 30.1489, -93.3356, '{"subsector": "electricity-generation", "epa_or_state_id": "25456999"}', 'org', now(), now())
on conflict (id) do update set name = excluded.name, facility_type = excluded.facility_type, latitude = excluded.latitude, longitude = excluded.longitude, metadata = excluded.metadata, visibility = excluded.visibility;

insert into facilities (id, org_id, slug, name, facility_type, latitude, longitude, metadata, visibility, created_at, updated_at)
values ('45d90864-78fd-533e-b4a6-479ddce7db40', '4f9c6696-1c12-52e3-b9c7-79d3db5e0063', 'lake-charles-polymers', 'Lake Charles Polymers', 'electricity-generation', 30.1966, -93.3219, '{"subsector": "electricity-generation", "epa_or_state_id": "25456949"}', 'org', now(), now())
on conflict (id) do update set name = excluded.name, facility_type = excluded.facility_type, latitude = excluded.latitude, longitude = excluded.longitude, metadata = excluded.metadata, visibility = excluded.visibility;

insert into facilities (id, org_id, slug, name, facility_type, latitude, longitude, metadata, visibility, created_at, updated_at)
values ('a9d66ee3-bd10-5c77-9ed7-f01682124772', 'bd206abe-875a-5a79-bfb0-9f83ae0f67ef', 'lake-charles-power', 'Lake Charles Power', 'electricity-generation', 30.2713, -93.2895, '{"subsector": "electricity-generation", "epa_or_state_id": "25457096"}', 'org', now(), now())
on conflict (id) do update set name = excluded.name, facility_type = excluded.facility_type, latitude = excluded.latitude, longitude = excluded.longitude, metadata = excluded.metadata, visibility = excluded.visibility;

insert into facilities (id, org_id, slug, name, facility_type, latitude, longitude, metadata, visibility, created_at, updated_at)
values ('0ffef057-26a3-5656-b101-93454990e082', 'f78a7b15-df16-5a21-9f18-b1cff3aa4382', 'lake-charles-regional-airport', 'Lake Charles Regional Airport', 'domestic-aviation', 30.126100540161133, -93.22329711914062, '{"subsector": "domestic-aviation", "epa_or_state_id": "3172558"}', 'org', now(), now())
on conflict (id) do update set name = excluded.name, facility_type = excluded.facility_type, latitude = excluded.latitude, longitude = excluded.longitude, metadata = excluded.metadata, visibility = excluded.visibility;

insert into facilities (id, org_id, slug, name, facility_type, latitude, longitude, metadata, visibility, created_at, updated_at)
values ('ee2e2da1-ae6c-57a4-95da-1f178d5bded0', 'f78a7b15-df16-5a21-9f18-b1cff3aa4382', 'lng-terminal-lake-charles-la', 'LNG Terminal Lake Charles,LA', 'domestic-shipping', 30.109879, -93.28729, '{"subsector": "domestic-shipping", "epa_or_state_id": "38902516"}', 'org', now(), now())
on conflict (id) do update set name = excluded.name, facility_type = excluded.facility_type, latitude = excluded.latitude, longitude = excluded.longitude, metadata = excluded.metadata, visibility = excluded.visibility;

insert into facilities (id, org_id, slug, name, facility_type, latitude, longitude, metadata, visibility, created_at, updated_at)
values ('6205135b-9890-5b0f-9c85-4b7fae48e709', 'f78a7b15-df16-5a21-9f18-b1cff3aa4382', 'lake-charles-louisiana', 'Lake Charles,Louisiana', 'domestic-shipping', 30.21922, -93.256641, '{"subsector": "domestic-shipping", "epa_or_state_id": "1934610"}', 'org', now(), now())
on conflict (id) do update set name = excluded.name, facility_type = excluded.facility_type, latitude = excluded.latitude, longitude = excluded.longitude, metadata = excluded.metadata, visibility = excluded.visibility;

insert into facility_daily_emissions (id, facility_id, measurement_date, tons_co2, measurement_type, created_at)
values ('2690918e-efc4-5460-b221-58c2e7274fe0', '81d3ce08-fa85-50ef-af7a-8f543fbdc21d', '2024-12-01', 12672.655591, 'actual', now())
on conflict (id) do update set tons_co2 = excluded.tons_co2, measurement_type = excluded.measurement_type;

insert into facility_daily_emissions (id, facility_id, measurement_date, tons_co2, measurement_type, created_at)
values ('7c8b7358-04da-551c-9732-60a2a5578939', '699dc94e-18c0-5075-a64d-44940613f9dd', '2024-12-01', 2322.242241, 'actual', now())
on conflict (id) do update set tons_co2 = excluded.tons_co2, measurement_type = excluded.measurement_type;

insert into facility_daily_emissions (id, facility_id, measurement_date, tons_co2, measurement_type, created_at)
values ('aad53705-3916-57d8-9aed-3db9ad6b55d7', '07839aab-ecf7-58f3-a7f7-064aaa27d77f', '2024-12-01', 2174.972986, 'actual', now())
on conflict (id) do update set tons_co2 = excluded.tons_co2, measurement_type = excluded.measurement_type;

insert into facility_daily_emissions (id, facility_id, measurement_date, tons_co2, measurement_type, created_at)
values ('9ace4594-a9fc-573d-9f9d-12950cc6a9ec', '39f7ccc0-25f9-5c43-8ee3-65a1ce6c08e2', '2024-12-01', 271.942023, 'actual', now())
on conflict (id) do update set tons_co2 = excluded.tons_co2, measurement_type = excluded.measurement_type;

insert into facility_daily_emissions (id, facility_id, measurement_date, tons_co2, measurement_type, created_at)
values ('b0ec7c19-eb6e-5393-b9d2-2c67a2e529d4', '2369cf61-6ef0-52cc-b1bf-ed1531092c0e', '2024-12-01', 3519.190883, 'actual', now())
on conflict (id) do update set tons_co2 = excluded.tons_co2, measurement_type = excluded.measurement_type;

insert into facility_daily_emissions (id, facility_id, measurement_date, tons_co2, measurement_type, created_at)
values ('15efc8e2-e634-5500-82c8-244056465a09', 'e7fc3e4f-1171-5a75-b451-7807d3be9255', '2024-12-01', 7038.381765, 'actual', now())
on conflict (id) do update set tons_co2 = excluded.tons_co2, measurement_type = excluded.measurement_type;

insert into facility_daily_emissions (id, facility_id, measurement_date, tons_co2, measurement_type, created_at)
values ('fd89ad8a-406d-512c-b4f3-ae1d56694683', '212fda08-74b9-5110-a424-35936d7c1cf0', '2024-12-01', 104.709677, 'actual', now())
on conflict (id) do update set tons_co2 = excluded.tons_co2, measurement_type = excluded.measurement_type;

insert into facility_daily_emissions (id, facility_id, measurement_date, tons_co2, measurement_type, created_at)
values ('eb20c68f-874f-59a3-a846-869df9b94c7b', '45d90864-78fd-533e-b4a6-479ddce7db40', '2024-12-01', 133.677419, 'actual', now())
on conflict (id) do update set tons_co2 = excluded.tons_co2, measurement_type = excluded.measurement_type;

insert into facility_daily_emissions (id, facility_id, measurement_date, tons_co2, measurement_type, created_at)
values ('e120a5d6-ffbb-569c-9881-4671866e4c47', 'a9d66ee3-bd10-5c77-9ed7-f01682124772', '2024-12-01', 3919.354839, 'actual', now())
on conflict (id) do update set tons_co2 = excluded.tons_co2, measurement_type = excluded.measurement_type;

insert into facility_daily_emissions (id, facility_id, measurement_date, tons_co2, measurement_type, created_at)
values ('41dc5764-68ac-5477-a8f6-2d9824d7be16', '0ffef057-26a3-5656-b101-93454990e082', '2024-12-01', 19.189767, 'actual', now())
on conflict (id) do update set tons_co2 = excluded.tons_co2, measurement_type = excluded.measurement_type;

insert into facility_daily_emissions (id, facility_id, measurement_date, tons_co2, measurement_type, created_at)
values ('0c006c9d-adbc-5b4d-a146-b1c732bae698', 'ee2e2da1-ae6c-57a4-95da-1f178d5bded0', '2024-12-01', 40.256831, 'actual', now())
on conflict (id) do update set tons_co2 = excluded.tons_co2, measurement_type = excluded.measurement_type;

insert into facility_daily_emissions (id, facility_id, measurement_date, tons_co2, measurement_type, created_at)
values ('63afe8ad-8808-555a-90f5-a9cb116d3380', '6205135b-9890-5b0f-9c85-4b7fae48e709', '2024-12-01', 119.144475, 'actual', now())
on conflict (id) do update set tons_co2 = excluded.tons_co2, measurement_type = excluded.measurement_type;

insert into emissions_aggregate (id, org_id, facility_id, period_start, period_end, scope, tons_co2_total, metadata, created_at)
values ('a2fa0f1c-807c-5759-9a2f-df7b60a68ec4', 'fa951fa4-2760-5db1-8a05-0b9ecfb2da67', '81d3ce08-fa85-50ef-af7a-8f543fbdc21d', '2024-01-01', '2024-12-31', 'facility', 4669623.08, '{"sector": "fossil-fuel-operations", "subsector": "oil-and-gas-refining", "year": 2024}', now())
on conflict (id) do update set tons_co2_total = excluded.tons_co2_total, metadata = excluded.metadata;

insert into emissions_aggregate (id, org_id, facility_id, period_start, period_end, scope, tons_co2_total, metadata, created_at)
values ('d71bcb66-2f00-50a4-bbfa-155afbb7c01f', 'f78a7b15-df16-5a21-9f18-b1cff3aa4382', '699dc94e-18c0-5075-a64d-44940613f9dd', '2024-01-01', '2024-12-31', 'facility', 862449.18, '{"sector": "fossil-fuel-operations", "subsector": "oil-and-gas-refining", "year": 2024}', now())
on conflict (id) do update set tons_co2_total = excluded.tons_co2_total, metadata = excluded.metadata;

insert into emissions_aggregate (id, org_id, facility_id, period_start, period_end, scope, tons_co2_total, metadata, created_at)
values ('6f73210d-ea55-55db-875f-d4400f73e221', 'f78a7b15-df16-5a21-9f18-b1cff3aa4382', '07839aab-ecf7-58f3-a7f7-064aaa27d77f', '2024-01-01', '2024-12-31', 'facility', 803093.00, '{"sector": "manufacturing", "subsector": "other-chemicals", "year": 2024}', now())
on conflict (id) do update set tons_co2_total = excluded.tons_co2_total, metadata = excluded.metadata;

insert into emissions_aggregate (id, org_id, facility_id, period_start, period_end, scope, tons_co2_total, metadata, created_at)
values ('c39dcc40-e235-5a80-ae96-58abc8d7f813', 'f78a7b15-df16-5a21-9f18-b1cff3aa4382', '39f7ccc0-25f9-5c43-8ee3-65a1ce6c08e2', '2024-01-01', '2024-12-31', 'facility', 100754.43, '{"sector": "manufacturing", "subsector": "other-manufacturing", "year": 2024}', now())
on conflict (id) do update set tons_co2_total = excluded.tons_co2_total, metadata = excluded.metadata;

insert into emissions_aggregate (id, org_id, facility_id, period_start, period_end, scope, tons_co2_total, metadata, created_at)
values ('58fad124-3ffc-571d-ab5a-b13a7c15ed9d', '5c60a4e0-dab5-5090-b0f5-435b4ff0cd7e', '2369cf61-6ef0-52cc-b1bf-ed1531092c0e', '2024-01-01', '2024-12-31', 'facility', 1269502.84, '{"sector": "manufacturing", "subsector": "petrochemical-steam-cracking", "year": 2024}', now())
on conflict (id) do update set tons_co2_total = excluded.tons_co2_total, metadata = excluded.metadata;

insert into emissions_aggregate (id, org_id, facility_id, period_start, period_end, scope, tons_co2_total, metadata, created_at)
values ('2157fbd1-c99d-5a09-888e-2b53a4d4fda4', 'dd092091-5a90-591d-97ad-ead8411a3205', 'e7fc3e4f-1171-5a75-b451-7807d3be9255', '2024-01-01', '2024-12-31', 'facility', 2539005.67, '{"sector": "manufacturing", "subsector": "petrochemical-steam-cracking", "year": 2024}', now())
on conflict (id) do update set tons_co2_total = excluded.tons_co2_total, metadata = excluded.metadata;

insert into emissions_aggregate (id, org_id, facility_id, period_start, period_end, scope, tons_co2_total, metadata, created_at)
values ('fa0c40c0-cffe-5cd0-abb4-824bb972e6bb', '7f206c78-abbb-5a9d-a6e9-e46aace4727d', '212fda08-74b9-5110-a424-35936d7c1cf0', '2024-01-01', '2024-12-31', 'facility', 35500.00, '{"sector": "power", "subsector": "electricity-generation", "year": 2024}', now())
on conflict (id) do update set tons_co2_total = excluded.tons_co2_total, metadata = excluded.metadata;

insert into emissions_aggregate (id, org_id, facility_id, period_start, period_end, scope, tons_co2_total, metadata, created_at)
values ('ff46257c-337d-5313-b6a8-70f0387f3454', '4f9c6696-1c12-52e3-b9c7-79d3db5e0063', '45d90864-78fd-533e-b4a6-479ddce7db40', '2024-01-01', '2024-12-31', 'facility', 45314.00, '{"sector": "power", "subsector": "electricity-generation", "year": 2024}', now())
on conflict (id) do update set tons_co2_total = excluded.tons_co2_total, metadata = excluded.metadata;

insert into emissions_aggregate (id, org_id, facility_id, period_start, period_end, scope, tons_co2_total, metadata, created_at)
values ('e796bba8-64e2-56ff-b7c1-eff40a9f9195', 'bd206abe-875a-5a79-bfb0-9f83ae0f67ef', 'a9d66ee3-bd10-5c77-9ed7-f01682124772', '2024-01-01', '2024-12-31', 'facility', 1337800.00, '{"sector": "power", "subsector": "electricity-generation", "year": 2024}', now())
on conflict (id) do update set tons_co2_total = excluded.tons_co2_total, metadata = excluded.metadata;

insert into emissions_aggregate (id, org_id, facility_id, period_start, period_end, scope, tons_co2_total, metadata, created_at)
values ('bbad803a-f71a-59ba-ae68-8db93750b883', 'f78a7b15-df16-5a21-9f18-b1cff3aa4382', '0ffef057-26a3-5656-b101-93454990e082', '2024-01-01', '2024-12-31', 'facility', 7454.47, '{"sector": "transportation", "subsector": "domestic-aviation", "year": 2024}', now())
on conflict (id) do update set tons_co2_total = excluded.tons_co2_total, metadata = excluded.metadata;

insert into emissions_aggregate (id, org_id, facility_id, period_start, period_end, scope, tons_co2_total, metadata, created_at)
values ('645280da-8c5f-53bc-b41f-71a0c524512c', 'f78a7b15-df16-5a21-9f18-b1cff3aa4382', 'ee2e2da1-ae6c-57a4-95da-1f178d5bded0', '2024-01-01', '2024-12-31', 'facility', 13397.76, '{"sector": "transportation", "subsector": "domestic-shipping", "year": 2024}', now())
on conflict (id) do update set tons_co2_total = excluded.tons_co2_total, metadata = excluded.metadata;

insert into emissions_aggregate (id, org_id, facility_id, period_start, period_end, scope, tons_co2_total, metadata, created_at)
values ('108a3cd7-fe34-5c34-ad9f-3a96c89e2ccd', 'f78a7b15-df16-5a21-9f18-b1cff3aa4382', '6205135b-9890-5b0f-9c85-4b7fae48e709', '2024-01-01', '2024-12-31', 'facility', 30575.60, '{"sector": "transportation", "subsector": "domestic-shipping", "year": 2024}', now())
on conflict (id) do update set tons_co2_total = excluded.tons_co2_total, metadata = excluded.metadata;

commit;
