# Generated by Django 4.2.7 on 2025-10-18 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmissionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "tons_co2_per_day",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("measurement_type", models.CharField(default="actual", max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emissions",
                        to="companies.company",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emissions",
                        to="companies.facility",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Emission Data",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("report_submitted", "Report Submitted"),
                            ("data_uploaded", "Data Uploaded"),
                            ("compliance_updated", "Compliance Updated"),
                            ("deadline_added", "Deadline Added"),
                            ("maintenance_scheduled", "Maintenance Scheduled"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activities",
                "ordering": ["-timestamp"],
            },
        ),
    ]
